# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ssot_winter_jubilee'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssot',
            name='transportation_needed',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
