# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-24 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_ssot_transportation_needed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ssot',
            old_name='transportation_needed',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='winter_jubilee',
            old_name='transportation_needed',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='ssot',
            name='need_transportation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winter_jubilee',
            name='need_transportation',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
